defaults:
  - model: gcn_pattern_100k

random_seed: 42
experiment_name: alinc-full
mlflow_dir: ./../experiments/full_training/
mlflow_db: full_training.db
num_workers: 0
logging: True
progressbar: False
status_interval: 1
debug_mode: False

dataset: pattern

optimizer: 
  name: Adam
  lr: 1e-3
  weight_decay: 0.0

primary_metric: acc_SBM
evaluator:
  name: multiclass_classification
  average: macro

early_stopping:
  mode: max
  patience: 20

output_dir: ./output/
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w
