name: alinc-github
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - setuptools_scm
  - wheel
  - rdkit
  - pip:
      - numpy
      - networkx
      - tqdm
      - hydra-core
      - omegaconf
      - mlflow
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - -f https://data.pyg.org/whl/torch-2.5.1+cu121.html
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu121
      - torchmetrics
      - torcheval
      - ogb
      - dal_toolbox @ git+https://github.com/dhuseljic/dal-toolbox.git
      - pytest
      - pytest-cov
      - -e .
