name: cluster
num_acq: 20
acq_size: 50
subset_size: 1000
num_init: null
node_encoder: embedding
primary_metric: acc_macro
is_undirected: True
evaluator: 
  name: multiclass_classification
  average: macro
early_stopping:
  mode: "max"
  patience: 20
eigen:
  max_freqs: 10
  norm_type: none
  eigvec_norm: L2
