name: gatedgcn_pyg
num_epochs: 200
train_batch_size: 64
predict_batch_size: 64
n_layers: 16
hidden_dim: 78
pos_enc: False
pos_enc_dim: 16
readout_type: mlp
optimizer: 
  name: AdamW
  lr: 1e-4
  weight_decay: 0.0
  clip_grad_norm: False
early_stopping:
  mode: "max"
  patience: 20
lr_scheduler:
  name: cosine