name: gatedgcn_lrgb
num_epochs: 500
train_batch_size: 64
predict_batch_size: 64
n_layers: 8
hidden_dim: 108
pos_enc: False
pos_enc_dim: 16
readout_type: mlp
optimizer: 
  name: Adam
  lr: 5e-4
  weight_decay: 0.0
  clip_grad_norm: False
early_stopping:
  mode: "max"
  patience: 20
lr_scheduler:
  name: cosine