name: gps
num_epochs: 100
train_batch_size: 16
predict_batch_size: 16
n_layers: 16
hidden_dim: 48
n_heads: 8
pos_enc: True
pos_enc_dim: 16
readout_type: mlp
dropout: 0.1
optimizer: 
  name: AdamW
  lr: 5e-4
  weight_decay: 1e-5
  clip_grad_norm: True
early_stopping:
  mode: "max"
  patience: 20
lr_scheduler:
  name: cosine_with_warmup
  warmup_steps: 5
  start_factor: 0.002